"""empty message

Revision ID: 42a0e98c4a5b
Revises: None
Create Date: 2016-08-18 00:49:36.296743

"""

# revision identifiers, used by Alembic.
revision = '42a0e98c4a5b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
