"""empty message

Revision ID: d37cf90ef0e8
Revises: 42a0e98c4a5b
Create Date: 2016-08-18 21:10:45.947849

"""

# revision identifiers, used by Alembic.
revision = 'd37cf90ef0e8'
down_revision = '42a0e98c4a5b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
